2_django_Social_Network/A/home/urls.py
from django.urls import path
from . import views

app_name= 'home'
urlpatterns= [
    path('' , views.HomeView.as_view(), name='home'),
    # path('',views.home, name='home')
    path('post/<int:post_id>/<slug:post_slug>/',views.PostDetailView.as_view(), name='post_detail'),
    path('post/delete/<int:post_id>/', views.PostDeleteView.as_view(), name='post_delete'),
    path('post/update/<int:post_id>/', views.PostUpdateView.as_view(), name='post_update'),
    path('post/create/', views.PostCreateView.as_view(), name='post_create'),
    path('reply/<int:post_id>/<int:comment_id>/', views.PostAddReplyView.as_view(), name='add_reply'),
    path('like/<int:post_id>/', views.PostLikeView.as_view(), name='post_like'),
]

2_django_Social_Network/A/home/templates/home/create.html
{% extends 'base.html'  %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Create">
    </form>
{% endblock %}

2_django_Social_Network/A/home/templates/home/detail.html
{% extends 'base.html'  %}
{% block content %}

    {% if request.user.id == post.user.id %}
        <a href="{% url 'home:post_delete' post.id %}" class="btn btn-danger"> Delete</a>
        <a href="{% url 'home:post_update' post.id %}" class="btn btn-info"> Updatye</a>
    {% endif %}
{#    <p>{{ post.user }}</p>#}
    <p> <a href="{% url "account:user_profile" post.user.id %}">{{ post.user.username }}</a>  - {{ post.updated | date:"Y-M" }}</p>
{#    <p>{{ post.user.email }}</p>#}
    <p>{{ post.body }}</p><hr/>

    {% if request.user.is_authenticated %}
        <a href="{% url 'home:post_like' post.id %}" class="{% if can_like %}disabled{% endif %} btn btn-primary col-md-2">Like {{ post.likes_count }}</a>
        <form action="" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send">
        </form> <br/>
     {% else %}
        <p class="alert alert-danger">Only logged in users can comment.</p>
    {% endif %}

{#    <p> {{ comments.count }} comments</p>#}
    {% for comment in comments %}
        <div class="card bg-dark text-white">
            <p class="card-header">{{ comment.user }} | {{ comment.created|timesince }}</p>
            <p class="card-body">{{ comment.body }}</p>

            {% if request.user.is_authenticated %}
                <form action="{% url 'home:add_reply' post.id comment.id %}" method="post" style="display:none;">
                    {% csrf_token %}
                    {{ reply_form.as_p }}
                    <input type="submit" value="send">
                </form> <br/>
            {% endif %}

            {% with replies=comment.rcomments.all %}
                {% for reply in replies  %}
                    <p class="bg-primary p-3 m-2">{{ reply.user }} <br/> {{ reply.body }}</p>
                {% endfor %}
            {% endwith %}

        </div> <br/>
    {% empty %}
        <p>No comments yet!      </p>
    {% endfor %}


{% endblock %}

2_django_Social_Network/A/home/templates/home/index.html
{% extends 'base.html'  %}
{#{% extends 'abc/base.html'  %}#}

{% block content %}
{#    index page#}

    <form action="" method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form><br/><br/>

    <div class=""card>
        {%  for post in posts %}
{#            <a href="{% url 'home:post_detail' post.id post.slug %}" class="card-body">{{ post.body | truncatewords:8 }}</a>#}
            <a href="{{ post.get_absolute_url }}" class="card-body">{{ post.body | truncatewords:8 }}</a>
        {% endfor %}
    </div>
{% endblock %}
</body>
</html>

2_django_Social_Network/A/home/templates/home/update.html
{% extends 'base.html'  %}

{% block content %}
    <form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Update">
    </form>
{% endblock %}